print("hello world")
print("what is your name?")
myName=input()
print("it is good to meet you," + myName)
print("the length of your name is:")
print(len(myName))
print("what is your age?")
myAge = input()
print("your will be " + str(int(myAge) + 1) + " in a year.")
